INSERT INTO bookstore.books (`ISBN`, `COSTPRICE`, `DESCRIPTION`, `FORMAT`, `GENRE`, `PUBYEAR`, `PUBLISHER`, `RETAILPRICE`, `STOCKLEVEL`, `TITLE`) 
	VALUES ('9781285425436', 10.99, 'a good book', 'Paperback', 'Study', 2013, 'Cengage', 100.99, 5, 'Electronic Commerce');	
INSERT INTO bookstore.books (`ISBN`, `COSTPRICE`, `DESCRIPTION`, `FORMAT`, `GENRE`, `PUBYEAR`, `PUBLISHER`, `RETAILPRICE`, `STOCKLEVEL`, `TITLE`) 
	VALUES ('9781285421234', 12.99, 'another good book', 'Paperback', 'Study', 2016, 'Nexus', 100.99, 5, 'Digital Commerce');		
	
INSERT INTO bookstore.authors (`ID`, `GIVENNAMES`, `SURNAME`) 
	VALUES (1, 'John', 'Smith');
INSERT INTO bookstore.authors (`ID`, `GIVENNAMES`, `SURNAME`) 
	VALUES (2, 'Erma', 'Jones');
	
INSERT INTO bookstore.sale (`DATELISTED`, `DURATION`, `ITEMCONDITION`, `POSTAGE`, `RESERVEPRICE`, `SALEPRICE`, `SALETYPE`, `STARTPRICE`, `ISBN_ISBN`, `BUYERID_ID`, `SELLERID_ID`, `PAYMENTID_ID`) 
	VALUES (CURRENT_TIMESTAMP, 7, 'Good', 2, 10, 10, 'Fixed', 1, '9781285425436', NULL, NULL, NULL);	
INSERT INTO bookstore.sale (`DATELISTED`, `DURATION`, `ITEMCONDITION`, `POSTAGE`, `RESERVEPRICE`, `SALEPRICE`, `SALETYPE`, `STARTPRICE`, `ISBN_ISBN`, `BUYERID_ID`, `SELLERID_ID`, `PAYMENTID_ID`)
	VALUES (CURRENT_TIMESTAMP, 7, 'Good', 5.0, 50.0, 0, 'Auction', 1, '9781285421234', NULL, NULL, NULL);

INSERT INTO bookstore.books ('ISBN', 'COSTPRICE', 'DESCRIPTION', 'FORMAT', 'GENRE', 'PUBYEAR', 'PUBLISHER', 'RETAILPRICE', 'STOCKLEVEL', 'TITLE') 
	VALUES ('9781285425436', 10.99, 'a good book', 'Paperback', 'Study', 2013, 'Cengage', 100.99, 5, 'Electronic Commerce');	
INSERT INTO bookstore.books ('ISBN', 'COSTPRICE', 'DESCRIPTION', 'FORMAT', 'GENRE', 'PUBYEAR', 'PUBLISHER', 'RETAILPRICE', 'STOCKLEVEL', 'TITLE') 
	VALUES ('9781285421234', 12.99, 'another good book', 'Paperback', 'Study', 2016, 'Nexus', 100.99, 5, 'Digital Commerce');		
	
INSERT INTO bookstore.authors ('ID', 'GIVENNAMES', 'SURNAME') 
	VALUES (1, 'John', 'Smith');
INSERT INTO bookstore.authors ('ID', 'GIVENNAMES', 'SURNAME') 
	VALUES (2, 'Erma', 'Jones');
	
INSERT INTO bookstore.sale ('DATELISTED', 'DURATION', 'ITEMCONDITION', 'POSTAGE', 'RESERVEPRICE', 'SALEPRICE', 'SALETYPE', 'STARTPRICE', 'ISBN_ISBN', 'BUYERID_ID', 'SELLERID_ID', 'PAYMENTID_ID') 
	VALUES (CURRENT_TIMESTAMP, 7, 'Fair', 2, 10.00, 10.00, 'Fixed', 1, '9781285425436', NULL, NULL, NULL);	
INSERT INTO bookstore.sale ('DATELISTED', 'DURATION', 'ITEMCONDITION', 'POSTAGE', 'RESERVEPRICE', 'SALEPRICE', 'SALETYPE', 'STARTPRICE', 'ISBN_ISBN', 'BUYERID_ID', 'SELLERID_ID', 'PAYMENTID_ID')
	VALUES (CURRENT_TIMESTAMP, 7, 'Good', 5.00, 50.00, 0, 'Auction', 1, '9781285421234', NULL, NULL, NULL);


